on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: e2e CI
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          docker swarm init
          docker network create --driver overlay --scope swarm infra
          cd ./ci
          docker stack deploy -c infra.yaml infra
          docker stack deploy -c th2-demo.yaml th2-demo
          until nc -vz localhost 32600
          do
            echo "Waiting for rabbitmq service"
            sleep 5
          done
