jobs:
  build:
    runs-on: windows-latest
    name: Python CI
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: pypy3.7
          architecture: x64
      - run: pin install -r requirements.txt
